config/routes.rb
Rails.application.routes.draw do
  root 'members#index'
  resources :gamefications, only: [:new, :create, :destroy, :edit, :update]
  resources :projects, except: [:show]
  get '/projects/:id/allocate', to: 'projects#allocate', as: 'allocate_project'
  post '/projects/:id/allocate', to: 'projects#associate', as: 'associate_project'
  delete '/projects/:id/allocate', to: 'projects#dessociate', as: 'dessociate_project'
  resources :members
  put '/members/:id/remove_assoc(.:format)', to: 'members#remove_assoc', as: 'member_remove_assoc'
  devise_for :members, :path => "/member" ,:skip => [:registrations]
  devise_scope :member do
    get "/member", to: "devise/sessions#new"
  end
  devise_for :admins, :path => "/admin", :skip => [:registrations]
  devise_scope :admin do
    get "/admin", to: "devise/sessions#new"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :members
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy, :allocate, :associate, :dessociate]
  before_action :authenticate!
  before_action :authenticate_admin!, only: [:edit, :update, :destroy, :associate, :dessociate]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def allocate
  end

  def associate
    @project.members << Member.find(params[:member_id])
    respond_to do |format|
      format.html { redirect_to allocate_project_path(@project), notice: 'Incluido' }
    end
  end

  def dessociate
    @project.members.delete(Member.find(params[:member_id]))
    respond_to do |format|
      format.html {redirect_to allocate_project_path(@project), notice: 'Removido'}
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :start, :finish, :member_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :start %>
    <%= form.date_select :start, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :finish %>
    <%= form.date_select :finish, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit :class => "btn btn-primary"%>
  </div>
<% end %>

app/views/projects/allocate.html.erb
<p>
  <strong>Name:</strong><br>
  <%= @project.name %>
</p>

<strong>Members:</strong><br>
<% if @project.members.empty? %>
  O projeto ainda não tem nenhum membro.
<% else %>
  <% @project.members.each do |m| %>
    <%= m.name %>
    <% if admin_signed_in? %>
      <%= link_to dessociate_project_path(:member_id => m.id), method: :delete do |f| %>
        <i class="fa fa-close"></i>
      <% end %>
    <% end %>
    <br>
  <% end %>
<% end %>
</p>
<% if admin_signed_in? %>
<p>
  <strong>Alocar membros</strong><br>
  <%= form_tag do %>
    <%= select_tag :member_id,
    options_from_collection_for_select(Member.all.where.not(:id => @project.member_ids),
    :id, :name), {:class => "form-control"} %><br>
    <%= submit_tag "Alocar", :class => "btn btn-success" %>
    <% end %>
</p>
<% end %>
<br><%= link_to 'Voltar', projects_path, :class => "btn btn-danger", :role => "button" %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path, :class => "btn btn-danger", :role => 'button' %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Número de Membros</th>
      <th scope="col">Start</th>
      <th scope="col">Finish</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.members.size %></td>
        <td><%= project.start %></td>
        <td><%= project.finish %></td>
        <td><%= link_to 'Ver', allocate_project_path(project), :class => 'btn btn-info', :role => 'button' %></td>
          <% if admin_signed_in? %>
        <td><%= link_to 'Edit', edit_project_path(project), :class => 'btn btn-primary', :role => 'button' %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger', :role => 'button' %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h4><%= link_to 'New Project', new_project_path, :class => 'btn btn-success', :role => 'button' if admin_signed_in? %></h4>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path, :class => "btn btn-danger", :role => 'button' %>