config/routes.rb
Rails.application.routes.draw do
  root 'members#index'
  resources :gamefications, only: [:new, :create, :destroy, :edit, :update]
  resources :projects, except: [:show]
  get '/projects/:id/allocate', to: 'projects#allocate', as: 'allocate_project'
  post '/projects/:id/allocate', to: 'projects#associate', as: 'associate_project'
  delete '/projects/:id/allocate', to: 'projects#dessociate', as: 'dessociate_project'
  resources :members
  put '/members/:id/remove_assoc(.:format)', to: 'members#remove_assoc', as: 'member_remove_assoc'
  devise_for :members, :path => "/member" ,:skip => [:registrations]
  devise_scope :member do
    get "/member", to: "devise/sessions#new"
  end
  devise_for :admins, :path => "/admin", :skip => [:registrations]
  devise_scope :admin do
    get "/admin", to: "devise/sessions#new"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_lte_2_header.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <a href="/" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>A</b>LT</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Admin</b>LTE</span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top justify-between" role="navigation">
    <% if admin_signed_in? %>
      <span class="navbar-text">Logado como <%= current_admin.email%></span>
      <span class="navbar-text"><%= link_to 'Deslogar', destroy_admin_session_path, method: :delete, :class => "logout" %></span>
    <% end %>
  </nav>
</header>

app/views/layouts/_admin_lte_2_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <% if member_signed_in? %>
      <div class="user-panel">
        <div class="pull-left image">
          <img src="<%= current_member.avatar%>" alt="User Image" />
        </div>
        <div class="pull-left info">
          <p><%= current_member.name %></p>
          <p><%= link_to 'Deslogar', destroy_member_session_path, method: :delete %>
        </div>
      </div>
    <% end %>

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">Ver</li>
        <!-- Optionally, you can add icons to the links -->
      <li><a href="/projects"><i class='fa fa-link'></i> <span>Projetos</span></a></li>
      <li><a href="/members"><i class='fa fa-link'></i> <span>Membros</span></a></li>
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin_lte_2.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>GTi</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>

<body class="skin-blue sidebar-mini fixed <%= params[:controller].parameterize %> <%= action_name %>">
  <div class="wrapper">

    <%= render partial: 'layouts/admin_lte_2_header' %>

    <%= render partial: 'layouts/admin_lte_2_sidebar' %>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

      <!-- Main content -->
      <section class="content">
        <% if notice %>
          <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= notice %></b>
          </div>
        <% end %>

        <% if alert %>
          <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= alert %></b>
          </div>
        <% end %>
        <%= yield %>
      </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

  </div><!-- ./wrapper -->

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trainee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>GTi | Log in</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>GT</b>i</a>
  </div><!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg"><%= yield %></p>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="form-group has-feedback">
        <%= f.text_field :email, class: 'form-control', autofocus: true %>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>

      <div class="form-group has-feedback">
        <%= f.password_field :password, class: 'form-control', autocomplete: 'off' %>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
        </div><!-- /.col -->
        <div class="col-xs-4">
          <%= f.submit 'Log in', class: 'btn btn-primary btn-block btn-flat' %>

        </div><!-- /.col -->
      </div>

    <% end %>
  </div><!-- /.login-box-body -->
</div><!-- /.login-box -->

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>