config/routes.rb
Rails.application.routes.draw do
  root 'members#index'
  resources :gamefications, only: [:new, :create, :destroy, :edit, :update]
  resources :projects, except: [:show]
  get '/projects/:id/allocate', to: 'projects#allocate', as: 'allocate_project'
  post '/projects/:id/allocate', to: 'projects#associate', as: 'associate_project'
  delete '/projects/:id/allocate', to: 'projects#dessociate', as: 'dessociate_project'
  resources :members
  put '/members/:id/remove_assoc(.:format)', to: 'members#remove_assoc', as: 'member_remove_assoc'
  devise_for :members, :path => "/member" ,:skip => [:registrations]
  devise_scope :member do
    get "/member", to: "devise/sessions#new"
  end
  devise_for :admins, :path => "/admin", :skip => [:registrations]
  devise_scope :admin do
    get "/admin", to: "devise/sessions#new"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_and_belongs_to_many :projects
  has_many :gamefications, :dependent => :destroy
  mount_uploader :avatar, AvatarUploader
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_admin!, only: [:create, :remove_assoc]
  before_action :authenticate!
  before_action :set_member, only: [:show, :edit, :update, :destroy, :remove_assoc ]
  require 'carrierwave/orm/activerecord'
  def index
    @membros = Member.all
  end

  def create
    @membro = Member.new(member_params.except(:project_id))
    respond_to do |format|
      if @membro.save
        format.html { redirect_to members_path, notice: 'Deu certo' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def new
    @membro = Member.new
  end

  def update
    respond_to do |format|
      if @membro.update(member_params.except(:project_id))
        format.html { redirect_to members_path, notice: 'Deu certo' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @membro.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Deu certo' }
    end
  end

  def remove_assoc
    sucesso = true
    if params[:project_id] != nil
      project = Project.find(params[:project_id])
      @membro.projects.delete(project)
    elsif params[:gamefication_id] != nil
      gamefication = Gamefication.find(params[:gamefication_id])
      @membro.gamefications.delete(gamefication)
    else
      sucesso = false
    end
    if sucesso
      respond_to do |format|
        format.html {redirect_to member_path(@membro), notice: 'Deletado'}
      end
    else
      respond_to do |format|
        format.html {redirect_to member_path(@membro), notice: '???'}
      end
    end
  end

  private

    def set_member
      @membro = Member.find(params[:id])
    end

    def member_params
      if params[:member][:password] == ''
        params.require(:member).permit(:name, :email, :project_id, :gamefication_id, :avatar)
      else
        params.require(:member).permit(:name, :email, :project_id, :password, :gamefication_id, :avatar)
      end
    end
  end

app/helpers/members_helper.rb
module MembersHelper
  def contar_pontos(membro)
    pos = 0
    neg = 0
    membro.gamefications.each do |g|
      if g.positive?
        pos += g.points
      else
        neg += g.points
      end
    end
    return [pos, neg]
  end

  def dessasociar_projeto(project_id)
    link_to member_remove_assoc_path(:project_id => project_id),
     data: { confirm: 'Are you sure?' }, method: :put do |f|
      content_tag(:i, "", class: "fa fa-close")
    end
  end

  def dessasociar_game(gamefication_id)
    link_to member_remove_assoc_path(:gamefication_id => gamefication_id),
     data: { confirm: 'Are you sure?' }, method: :put do |f|
      content_tag(:i, "", class: "fa fa-close")
     end
  end
end

app/views/members/_form.html.erb
<%= form_with(model: @membro, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, :class => "form-control" %>
  </div>
  <div class="custom-file">
  <%= form.label :avatar do |f| %>
    <%= form.file_field :avatar %>
  <% end %>
  </div>
  <div class="actions">
    <%= form.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/members/edit.html.erb
<% if member_signed_in? %>
  <% unless current_member.id == @membro.id %>
    <% controller.redirect_to @membro, notice: "Só o usuário pode modificar seu perfil" %>
  <% end %>
<% end %>
<h1>Editar membro</h1>
<br>
<%= render 'form', member: @membro %>

<%= link_to 'Back', member_path(@membro), :class => 'btn btn-danger', :role => 'button' %>

app/views/members/index.html.erb
<h1>Membros</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th scope="col">Nome</th>
      <th scope="col">Email</th>
      <th scope="col">Numero de Projetos</th>
      <th scope="col">Pontos (Positivo|Negativo)</th>
    </tr>
  </thead>
  <tbody>
    <% @membros.each do |membro| %>
      <tr scope="row">
        <td><img src="<%= membro.avatar.thumb %>"></td>
        <td><%= membro.name %></td>
        <td><%= membro.email %></td>
        <td><%= membro.projects.size %></td>
        <td><%= contar_pontos(membro).join(" | - ") %></td>
        <td><%= link_to 'Detalhes', membro, :class => 'btn btn-info', :role => 'button' %></td>
        <% if admin_signed_in? %>
          <td><%= link_to 'Adicionar pontos', new_gamefication_path(:member_id => membro.id), :class => 'btn btn-primary', :role => 'button' %>
          <td><%= link_to 'Destroy', membro, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger', :role => 'button' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h4><%= link_to 'Novo membro', new_member_path, :class => 'btn btn-success', :role => 'button' if admin_signed_in? %></h4>

app/views/members/new.html.erb
<h1>Criar membros</h1>
<br>
<%= render 'form', member: @membro %>

<%= link_to 'Back', members_path, :class => 'btn btn-danger', :role => 'button' %>

app/views/members/show.html.erb
<img src="<%= @membro.avatar.large %>">

<p>
  <strong>Name:</strong>
  <%= @membro.name %>
</p>

<p>
  <strong>Projetos:</strong><br>
  <% if @membro.projects.empty? %>
    O membro não está em nenhum projeto.
  <% else %>
    <% @membro.projects.each do |projeto| %>
      <%= projeto.name %> <%= dessasociar_projeto(projeto.id) if admin_signed_in? %><br>
    <% end %>
  <% end %>
  <%= link_to 'Gerenciar Projetos', projects_path if admin_signed_in? %>

</p>

<p>
  <strong>Gamefications:</strong><br>
  <% if @membro.gamefications.empty? %>
    O membro não tem pontos ainda.
  <% else %>
    <% pos = 0 %>
    <% neg = 0 %>
    <% @membro.gamefications.each do |gamefication| %>
      <%= gamefication.reason %>,
      <% if gamefication.positive? %>
         <%= gamefication.points%> pontos.
        <% pos += gamefication.points %>
      <% else %>
         - <%= gamefication.points%> pontos.
        <% neg += gamefication.points %>
      <% end %>
      <% if admin_signed_in? %>
        <%= link_to edit_gamefication_path(gamefication.id) do |f| %>
          <i class="fa fa-edit"></i>
        <% end %>|
        <%= dessasociar_game(gamefication.id) %><br>
      <% end %>
    <% end %>
  <% end %>
  <%= link_to 'Adicionar pontos', new_gamefication_path(:member_id => @membro.id) if admin_signed_in? %>
</p>
<div class="btn-group" role="group">
  <%= link_to 'Edit', edit_member_path(@membro), :class => 'btn btn-primary' %>
  <%= link_to 'Back', members_path, :class => 'btn btn-danger' %>
</div>